spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  opensearch:
    url: http://opensearch:9200

nacos:
  server-addr: nacos:8848

rocketmq:
  endpoints: "rmq-proxy:18080"
  document-index-topic: "topic_saa_studio_document_index"
  document_index_group: "group_saa_studio_document_index"
