import React, { useState } from 'react';
import {
  Modal,
  Card,
  Typography,
  Button,
  Alert,
  Space,
  Tabs,
  Avatar,
  message
} from 'antd';
import {
  CheckCircleOutlined,
  CloseOutlined,
  InfoCircleOutlined,
  CopyOutlined,
  BulbOutlined,
  CodeOutlined,
} from '@ant-design/icons';

const { Title, Text, Paragraph } = Typography;

const PublishSuccessModal = ({ prompt, version, onClose }) => {
  console.log(prompt, 'zxc...')
  const [activeTab, setActiveTab] = useState('integration');

  const tabs = [
    { key: 'integration', label: 'Integration Guide', icon: <CodeOutlined /> }
  ];

  const integrationCode1 = `<dependency>
  <groupId>com.alibaba.cloud.ai</groupId>
  <artifactId>spring-ai-alibaba-agent-nacos</artifactId>
  <version>{spring.ai.alibaba.version}</version>
</dependency>
`


  const integrationCode2 = `spring.ai.alibaba.agent.proxy.nacos.serverAddr={ Replace with nacos address, e.g.: 127.0.0.1:8848}
spring.ai.alibaba.agent.proxy.nacos.username={ Replace with nacos username, e.g.: nacos}
spring.ai.alibaba.agent.proxy.nacos.password={ Replace with nacos password, e.g.: nacos}
spring.ai.alibaba.agent.proxy.nacos.promptKey={ Replace with promptKey, e.g.: mse-nacos-helper }`;

  const integrationCode3 = `<dependency>
	<groupId>com.alibaba.cloud.ai</groupId>
	<artifactId>spring-ai-alibaba-autoconfigure-arms-observation</artifactId>
	<version>{spring.ai.alibaba.version}</version>
</dependency>


<!-- For auto-loading various OTel components such as Tracer and Exporter -->
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>

<!-- For converting micrometer metric data to otlp format -->
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-registry-otlp</artifactId>
</dependency>

<!-- For replacing micrometer's underlying tracing tracer with OTel tracer -->
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-tracing-bridge-otel</artifactId>
</dependency>

<!-- For reporting spans generated by OTel tracer according to otlp protocol -->
<dependency>
	<groupId>io.opentelemetry</groupId>
	<artifactId>opentelemetry-exporter-otlp</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.ai</groupId>
	<artifactId>spring-ai-autoconfigure-model-tool</artifactId>
	<version>1.0.0</version>
</dependency>`;

  const integrationCode4 = `management.otlp.tracing.export.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://{studio address}:4318/v1/traces
management.otlp.metrics.export.enabled=false
management.otlp.logging.export.enabled=false
management.opentelemetry.resource-attributes.service.name=agent-nacos-prompt-test
management.opentelemetry.resource-attributes.service.version=1.0
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true
spring.ai.image.observations.log-prompt=true
spring.ai.vectorstore.observations.log-query-response=true
spring.ai.alibaba.arms.enabled=true
spring.ai.alibaba.arms.tool.enabled=true
spring.ai.alibaba.arms.model.capture-input=true
spring.ai.alibaba.arms.model.capture-output=true`;

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text).then(() => {
      message.success('Copied successfully');
    }).catch(() => {
      message.error('Copy failed');
    });
  };

  return (
    <Modal
      open={true}
      onCancel={onClose}
      footer={null}
      width={1200}
      style={{
        top: 20,
        maxHeight: 'calc(100vh - 40px)',
        overflow: 'hidden'
      }}
      bodyStyle={{
        maxHeight: 'calc(100vh - 200px)',
        overflowY: 'auto',
        padding: 0
      }}
      closeIcon={<CloseOutlined />}
    >
      <div>
        {/* Success prompt header */}
        <div style={{
          padding: '24px',
          borderBottom: '1px solid #f0f0f0',
          background: 'linear-gradient(135deg, #f6ffed 0%, #e6f7ff 100%)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
              <Avatar
                size={48}
                style={{ backgroundColor: '#f6ffed', color: '#52c41a' }}
                icon={<CheckCircleOutlined />}
              />
              <div>
                <Title level={2} style={{ margin: 0, color: '#262626' }}>Published Successfully!</Title>
                <Paragraph style={{ margin: '4px 0 0 0', color: '#595959' }}>
                  Prompt <Text style={{ fontWeight: 500, color: '#52c41a' }}>{prompt.promptKey}</Text>{' '}
                  version <Text style={{ fontWeight: 500, color: '#52c41a' }}>{version}</Text> has been successfully published
                </Paragraph>
              </div>
            </div>
          </div>
        </div>

        {/* Tab navigation */}
        <Tabs
          activeKey={activeTab}
          onChange={setActiveTab}
          items={tabs.map(tab => ({
            key: tab.key,
            label: (
              <span>
                {tab.icon}
                <span style={{ marginLeft: 8 }}>{tab.label}</span>
              </span>
            ),
            children: null
          }))}
          style={{
            borderBottom: '1px solid #f0f0f0',
            backgroundColor: '#fafafa',
            margin: 0
          }}
          tabBarStyle={{
            paddingLeft: 24,
            paddingRight: 24,
            margin: 0
          }}
        />

        {/* Content area */}
        <div style={{ padding: 24 }}>
          {activeTab === 'integration' && (
            <Space direction="vertical" size={24} style={{ width: '100%' }}>
              <Alert
                message={
                  <div>
                    Prompt published successfully, <span className='text-xs'>Version Type:</span>
                    <Text strong>{prompt.latestVersionStatus === 'release' ? 'Release Version' : 'PRE Version'}</Text>
                  </div>
                }
                description={
                  prompt.latestVersionStatus === "release" ? (
                    <div>
                      <Text>The current Prompt version has been published to Nacos:</Text>
                      <div style={{
                        marginTop: 8,
                        padding: 12,
                        backgroundColor: '#f6ffed',
                        borderRadius: 6,
                        fontSize: '13px',
                        fontFamily: 'monospace'
                      }}>
                        <div>group：<Text strong>nacos-ai-meta</Text></div>
                        <div>dataID：<Text strong>prompt-{prompt.promptKey || '-'}.json</Text></div>
                      </div>
                    </div>
                  )
                  : (
                    <Text>Prompt PRE version published successfully. You can conduct laboratory evaluation on the PRE version Prompt, and publish a release version after evaluation meets expectations</Text>
                  )

                }
                type="success"
                icon={<CheckCircleOutlined />}
                showIcon
              />

              <Alert
                message="Spring AI Alibaba Integration Guide"
                description="Spring AI Alibaba Agent integrates with Nacos to implement prompt loading and dynamic updates."
                type="info"
                icon={<InfoCircleOutlined />}
                showIcon
              />

              <Title level={4} style={{ margin: 0 }}>
                Step 1 Create SpringBoot Project
              </Title>
              <div>
                <span className='text-red-600'>*</span>
                For spring.ai.alibaba.version, please refer to the spring-ai-alibaba official website
              </div>
              <Card
                title={
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <Text strong>1. Import spring ai alibaba agent nacos proxy module</Text>
                    <Button
                      type="default"
                      size="small"
                      icon={<CopyOutlined />}
                      onClick={() => copyToClipboard(integrationCode1)}
                    >
                      Copy Code
                    </Button>
                  </div>
                }
                bodyStyle={{ padding: 0 }}
              >
                <div style={{
                  backgroundColor: '#1f1f1f',
                  padding: 16,
                  overflowX: 'auto'
                }}>
                  <pre style={{
                    color: '#4ade80',
                    fontSize: '13px',
                    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
                    whiteSpace: 'pre-wrap',
                    margin: 0
                  }}>
                    {integrationCode1}
                  </pre>
                </div>
              </Card>

              <Card
                title={
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <Text strong>2. Specify nacos address and promptKey</Text>
                    <Button
                      type="default"
                      size="small"
                      icon={<CopyOutlined />}
                      onClick={() => copyToClipboard(integrationCode3)}
                    >
                      Copy Code
                    </Button>
                  </div>
                }
                bodyStyle={{ padding: 0 }}
              >
                <div style={{
                  backgroundColor: '#1f1f1f',
                  padding: 16,
                  overflowX: 'auto'
                }}>
                  <pre style={{
                    color: '#4ade80',
                    fontSize: '13px',
                    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
                    whiteSpace: 'pre-wrap',
                    margin: 0
                  }}>
                    {integrationCode2}
                  </pre>
                </div>
              </Card>
              <Card
                title={
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <Text strong>4. Set observability parameters</Text>
                    <Button
                      type="default"
                      size="small"
                      icon={<CopyOutlined />}
                      onClick={() => copyToClipboard(integrationCode2)}
                    >
                      Copy Code
                    </Button>
                  </div>
                }
                bodyStyle={{ padding: 0 }}
              >
                <div style={{
                  backgroundColor: '#1f1f1f',
                  padding: 16,
                  overflowX: 'auto'
                }}>
                  <pre style={{
                    color: '#4ade80',
                    fontSize: '13px',
                    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
                    whiteSpace: 'pre-wrap',
                    margin: 0
                  }}>
                    {integrationCode3}
                  </pre>
                </div>
              </Card>
              <Card
                title={
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <Text strong>3. Import spring ai alibaba observability module</Text>
                    <Button
                      type="default"
                      size="small"
                      icon={<CopyOutlined />}
                      onClick={() => copyToClipboard(integrationCode4)}
                    >
                      Copy Code
                    </Button>
                  </div>
                }
                bodyStyle={{ padding: 0 }}
              >
                <div style={{
                  backgroundColor: '#1f1f1f',
                  padding: 16,
                  overflowX: 'auto'
                }}>
                  <pre style={{
                    color: '#4ade80',
                    fontSize: '13px',
                    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
                    whiteSpace: 'pre-wrap',
                    margin: 0
                  }}>
                    {integrationCode4}
                  </pre>
                </div>
                <div className='p-2'>
                  <span className='text-red-600'>*</span>
                  {`Please replace {studio address} with the actual address`}
                </div>
              </Card>

              <Title level={4} style={{ margin: 0 }}>
                Step 2 Create SpringBoot Project
              </Title>

              <Card>
                <div>
                  <Text>
                    Build ReactAgent specifying builderFactory as NacosAgentPromptBuilderFactory
                  </Text>
                </div>
                <div>
                  <Text>
                    ReactAgent.builder(new NacosAgentPromptBuilderFactory(nacosOptions))
                  </Text>
                </div>
                <div>
                  Notes:
                  <ol>
                    <li>
                      nacosOptions type is NacosOptions, can be imported via standard Spring Bean mode
                    </li>
                    <li>
                      By default, ReactAgent.builder() uses DefaultBuilder internally. By specifying NacosAgentPromptBuilderFactory(nacosOptions), the prompt template corresponding to promptKey will be loaded from nacos during build, and supports dynamic prompt updates.
                    </li>
                    <li>
                      Other parameters for building ReactAgent are consistent with the standard ReactAgent build method.
                    </li>
                  </ol>
                </div>
              </Card>
            </Space>
          )}

        </div>

        {/* Footer action area */}
        <div style={{
          padding: 24,
          borderTop: '1px solid #f0f0f0',
          backgroundColor: '#fafafa',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          position: 'sticky',
          bottom: 0
        }}>
          <div style={{ display: 'flex', alignItems: 'center', color: '#595959', fontSize: '14px' }}>
            <BulbOutlined style={{ color: '#faad14', marginRight: 4 }} />
            Tip: After configuration updates, the application will automatically reload the latest Prompt configuration
          </div>
          <Space>
            <Button
              type="primary"
              onClick={onClose}
            >
              Complete
            </Button>
          </Space>
        </div>
      </div>
    </Modal>
  );
};

export default PublishSuccessModal;
