/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.cloud.ai.studio.admin.builder.generator.service.generator.workflow;

import java.io.InputStream;
import java.util.List;
import java.util.function.Supplier;

import com.alibaba.cloud.ai.studio.admin.builder.generator.model.workflow.Edge;
import com.alibaba.cloud.ai.studio.admin.builder.generator.model.workflow.Node;
import com.alibaba.cloud.ai.studio.admin.builder.generator.model.workflow.NodeData;
import com.alibaba.cloud.ai.studio.admin.builder.generator.model.workflow.NodeType;
import com.alibaba.cloud.ai.studio.admin.builder.generator.service.dsl.DSLDialectType;

/**
 * Render a node data
 *
 * @author robocanic
 * @since 2025/5/23
 */
//TODO: Put the code generated by assistMethodCode in a separate class in the generated project
public interface NodeSection<T extends NodeData> {

	boolean support(NodeType nodeType);

	//TODO: There is a varName field in NodeData, remove the varName parameter
	String render(Node node, String varName);

	/**
	 * Returns a list of classes that need to be imported for the current node
	 * @return class list
	 */
	List<String> getImports();

	default String escape(String input) {
		if (input == null) {
			return "";
		}
		return input.replace("\\", "\\\\")
			.replace("\"", "\\\"")
			.replace("\n", "\\n")
			.replace("\r", "\\r")
			.replace("\t", "\\t");
	}

	/**
	 * Code to generate stateGraph edges.The edge list is the edge starting from the current node.If the current node has conditional edges, this method should be overridden.This method defaults to unconditional edges.
	 * @param nodeData Data of the current node (edge ​​starting node)
	 * @param edges edge list, and edge source and handle should be formatted as varName
	 * @return generated code
	 */
	default String renderEdges(T nodeData, List<Edge> edges) {
		StringBuilder sb = new StringBuilder();
		sb.append(String.format("// Edges For [%s]%n", nodeData.getVarName()));
		if (edges.isEmpty()) {
			return "";
		}
		sb.append(String.format("stateGraph%n"));
		edges.forEach(
				edge -> sb.append(String.format(".addEdge(\"%s\", \"%s\")%n", edge.getSource(), edge.getTarget())));
		sb.append(String.format(";%n%n"));
		return sb.toString();
	}

	/**
	 * Common auxiliary code for nodes of the current type. This code will be generated before the node code.
	 * @param dialectType DSL type
	 * @return auxiliary code
	 */
	default String assistMethodCode(DSLDialectType dialectType) {
		return "";
	}

	record ResourceFile(String fileName, Type type, Supplier<InputStream> inputStreamSupplier) {

		@Override
		public String toString() {
			return String.format("\"%s\"", switch (type()) {
				case CLASS_PATH -> "classpath:" + fileName();
				default -> fileName();
			});
		}
		public enum Type {

			LOCAL, URL, CLASS_PATH

		}
	}

	/**
	 * Some nodes require additional resource files
	 * @param dialectType DSL type
	 * @param nodeData node data
	 * @return resource file list
	 */
	default List<ResourceFile> resourceFiles(DSLDialectType dialectType, T nodeData) {
		return List.of();
	}

}
